version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-24/de-minimal-rhel9:latest'

dependencies:
  galaxy:
    collections:
      - ansible.eda
  python_interpreter:
    package_system: "python3"
  system:
    - gcc
    - pkgconfig
    - python3-devel
    - systemd-devel

options:
  package_manager_path: /usr/bin/microdnf
