---
- name: Test1
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5050
        token: verysecuretoken
  rules:
    - name: Print all
      condition: True
      actions:
        - debug:
            msg: '{{ event }}'
